load("@com_nvidia_isaac_sdk//bzl:module.bzl", "isaac_app")

isaac_app(
  name = "depthvista_camera",
  modules = [
   "depthvista",
   "imu",
   "hgmm",
   "rgbd_processing",
   "sight",
   "viewers"
  ]
)
